# Generated by Django 4.1.2 on 2022-10-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congregacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('primer_nombre', models.TextField()),
                ('segundo_nombre', models.TextField(null=True)),
                ('primer_apellido', models.TextField()),
                ('segundo_apellido', models.TextField(null=True)),
                ('apellido_casada', models.TextField(null=True)),
                ('nombre_completo', models.TextField()),
                ('anios_congregados', models.IntegerField(null=True)),
                ('anios', models.IntegerField(null=True)),
                ('direccion', models.TextField(blank=True, max_length=100, null=True)),
                ('municio', models.TextField(blank=True, max_length=15, null=True)),
                ('departamento', models.TextField(blank=True, max_length=15, null=True)),
                ('ministerios', models.TextField(blank=True, null=True)),
                ('fecha_bautizado', models.DateField(blank=True, null=True)),
                ('img_bautizado', models.FileField(upload_to='images/bautizado/')),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_ingreso_bd', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sicar_congregacion',
                'verbose_name_plural': 'sicar_congregacion',
                'db_table': 'sicar_congregacion',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'continentes',
                'verbose_name_plural': 'continentes',
                'db_table': 'continentes',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'gastos',
                'verbose_name_plural': 'gastos',
                'db_table': 'gastos',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'lideres',
                'verbose_name_plural': 'lideres',
                'db_table': 'lideres',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ministerios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('lider', models.TextField(blank=True, null=True)),
                ('disponible_presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'ministerios',
                'verbose_name_plural': 'ministerios',
                'db_table': 'ministerios',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'paises',
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion_response', models.JSONField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'votaciones',
                'verbose_name_plural': 'votaciones',
                'db_table': 'votaciones',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VotacionesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('candidatos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'votacionesadmin',
                'verbose_name_plural': 'votacionesadmin',
                'db_table': 'votacionesadmin',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.paises')),
            ],
            options={
                'verbose_name': 'departamentos',
                'verbose_name_plural': 'departamentos',
                'db_table': 'departamentos',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
