# Generated by Django 4.1.2 on 2022-10-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ministerios'),
        ),
        migrations.AddField(
            model_name='lideres',
            name='Ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ministerios'),
        ),
        migrations.AddField(
            model_name='lideres',
            name='code_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.congregacion'),
        ),
        migrations.AddField(
            model_name='paises',
            name='continente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.continentes'),
        ),
        migrations.AddField(
            model_name='votaciones',
            name='code_hermano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.congregacion'),
        ),
        migrations.AddField(
            model_name='votaciones',
            name='code_votacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.votacionesadmin'),
        ),
        migrations.AddField(
            model_name='votacionesadmin',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ministerios'),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.departamentos'),
        ),
    ]
