# Generated by Django 4.1.2 on 2022-10-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gastos_ministerio_lideres_ministerio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacion',
            name='ministerios',
        ),
        migrations.AddField(
            model_name='congregacion',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ministerios'),
        ),
    ]
