# Generated by Django 4.1.2 on 2022-10-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_congregacion_ministerios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacion',
            name='apellido_casada',
            field=models.CharField(default='NA', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='nombre_completo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='primer_apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='primer_nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='segundo_apellido',
            field=models.CharField(default='NA', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='congregacion',
            name='segundo_nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='continentes',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.congregacion'),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paises',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='votacionesadmin',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
