# Generated by Django 4.1.2 on 2022-10-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_congregacion_apellido_casada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacion',
            name='municio',
        ),
        migrations.AddField(
            model_name='congregacion',
            name='municipio',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
