# Generated by Django 4.1.2 on 2022-10-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_congregacion_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
